routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::middleware('language')->group(function () {
    Route::get('/', [\App\Http\Controllers\PostsController::class, 'index']);

    Route::resource('posts', \App\Http\Controllers\PostsController::class)->except(['show', 'destroy'])->middleware('auth');

    Auth::routes();
});

Route::get('language/{locale}',
    [\App\Http\Controllers\LanguageSwitcherController::class, 'switcher']
)->name('language.switcher')->where('locale', 'en|ru');

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;

class Post extends Model implements TranslatableContract
{
    use HasFactory, Translatable;

    public $translatedAttributes = ['body'];
    protected $fillable = ['user_id'];

    /**
     * @return BelongsTo
     */
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Models/PostTranslation.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class PostTranslation extends Model
{
    use HasFactory;

    public $timestamps = false;
    protected $fillable = ['body'];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * @return HasMany
     */
    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/LanguageSwitcherController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class LanguageSwitcherController extends Controller
{
    /**
     * @param Request $request
     * @param string $locale
     * @return RedirectResponse
     */
    public function switcher(Request $request, string $locale)
    {
        $request->session()->put('locale', $locale);
        return back();
    }
}

app/Http/Controllers/PostsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class PostsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Factory|View|Response
     */
    public function index()
    {
        $posts = Post::all();
        return view('posts.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Factory|View|Response
     */
    public function create()
    {
        return view('posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\RedirectResponse|Response
     */
    public function store(Request $request)
    {
        $post = new Post($request->all());
        $post->user()->associate($request->user());
        $post->save();
        return redirect()->route('posts.index')->with('status', trans('messages.created'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return Factory|View|Response
     */
    public function edit(Post $post)
    {
        return view('posts.edit', compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Post $post
     * @return \Illuminate\Http\RedirectResponse|Response
     */
    public function update(Request $request, Post $post)
    {
        $post->update($request->all());
        return redirect()->route('posts.index')->with('status', trans('messages.updated'));
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    @lang('messages.laravel')
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        <select class="custom-select" onchange="location = this.value;">
                            <option @if (session('locale') == 'en') selected @endif value="{{route('language.switcher', 'en')}}">
                                EN
                            </option>
                            <option @if (session('locale') == 'ru') selected @endif value="{{route('language.switcher', 'ru')}}">
                                RU
                            </option>
                        </select>
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">@lang('messages.login')</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">@lang('messages.register')</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        @lang('messages.logout')
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            <div class="container">
                @if (session('status'))
                    <div class="alert alert-primary" role="alert">
                        {{session('status')}}
                    </div>
                @endif
            @yield('content')
            </div>
        </main>
    </div>
</body>
</html>

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('content')

    <form action="{{route('posts.store')}}" method="post">
        @csrf

        <div class="form-group">
            <label for="ru[body]">@lang('messages.enter_phrase')</label>
            <input required class="form-control" type="text" name="ru[body]" id="ru[body]">
        </div>
        <br>
        <button class="btn btn-outline-primary" type="submit">@lang('messages.save')</button>

    </form>

@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')

@section('content')

    <form action="{{route('posts.update', ['post' => $post])}}" method="post">
        @method('put')
        @csrf

        <div class="form-group">
            <label for="ru[body]">@lang('messages.enter_phrase')</label>
            <input class="form-control" disabled type="text" name="ru[body]" id="ru[body]" value="{{$post->translate('ru')->body}}">
        </div>

        <div class="form-group">
            <label for="en[body]">@lang('messages.enter_translate_en')</label>
            <input required class="form-control" type="text" name="en[body]" id="en[body]">
        </div>

        <div class="form-group">
            <label for="fr[body]">@lang('messages.enter_translate_fr')</label>
            <input required class="form-control" type="text" name="fr[body]" id="fr[body]">
        </div>

        <div class="form-group">
            <label for="de[body]">@lang('messages.enter_translate_de')</label>
            <input required class="form-control" type="text" name="de[body]" id="de[body]">
        </div>

        <div class="form-group">
            <label for="cz[body]">@lang('messages.enter_translate_cz')</label>
            <input required class="form-control" type="text" name="cz[body]" id="cz[body]">
        </div>
        <br>
        <button class="btn btn-outline-primary" type="submit">@lang('messages.save')</button>

    </form>

@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('content')

    @if(Auth::check())
    <h1>
        @lang('messages.hello') {{Auth::user()->name}}
    </h1>



    <a href="{{route('posts.create')}}">@lang('messages.add_new_post')</a>

    @foreach($posts as $post)
        @if($post->translations()->get()->count() < 5)
            <ul class="border-dark border my-3">
                <li>
                    {{$post->translate('ru')->body}} | <a href="{{route('posts.edit', ['post' => $post])}}">@lang('messages.translate')</a>
                </li>
            </ul>
        @endif
    @endforeach

    @endif

    @if($posts->count()>0)


        <table class="table">
            <thead>
            <tr>
                <th>#</th>
                <th>RU</th>
                <th>EN</th>
                <th>FR</th>
                <th>DE</th>
                <th>CZ</th>
            </tr>
            </thead>
            <tbody>
            @foreach($posts as $post)
                @if($post->translations()->get()->count() == 5)
            <tr>
                <td>{{$post->id}}</td>
                <td>{{$post->translate('ru')->body}}</td>
                <td>{{$post->translate('en')->body}}</td>
                <td>{{$post->translate('fr')->body}}</td>
                <td>{{$post->translate('de')->body}}</td>
                <td>{{$post->translate('cz')->body}}</td>
            </tr>
                @endif
            @endforeach
            </tbody>
        </table>

    @else

        <p>No posts</p>

    @endif

@endsection